export const COL_ORDER: {
  saci: (keyof SACIData)[],
} = {
  saci: [
    'date',
    'acft',
    'studentCanac',
    'dep',
    'arr',
    'tTotal',
    'tDay',
    'tNight',
    'tNav',
    'tIFR',
    'tCapt',
    'ldg',
    'NM',
    'func',
    'obs',
    'status',
    'reg',
    'exclusionDate',
    'excludedBy',
    'id',
  ],
};

export const COLMAP_NAMES: {
  [K in keyof SACIData]: string
} = {
  id: 'id',
  date: 'Data',
  acft: 'ACFT',
  crew: 'Tripulante',
  studentCanac: 'CANAC',
  dep: 'Origem',
  arr: 'Destino',
  tTotal: 'Total',
  tDay: 'DIU',
  tNight: 'NOT',
  tNav: 'NAV',
  tIFR: 'INST',
  tCapt: 'CAPT',
  ldg: 'Pousos',
  NM: 'Milhas',
  func: 'Função',
  obs: 'OBS',
  status: 'Status',
  reg: 'Cadastrado',
  exclusionDate: 'Exclusão',
  excludedBy: 'Excluido por',
};

export const COLMAP_INDEX = {
  saci: {
    date: 0,
    acft: 1,
    crew: 4,
    dep: 6,
    arr: 7,
    tDay: 10,
    tNight: 11,
    tNav: 12,
    tIFR: 13,
    tCapt: 14,
    ldg: 5,
    NM: 16,
    func: 9,
    obs: 8,
    status: 18,
    reg: 19,
    exclusionDate: 20,
    excludedBy: 21,
  },
  saas: {
    date: 1,
    acft: 4,
    crew: 2,
    depArr: 5,
    tTotal: 6,
    tDay: 7,
    tNight: 8,
    tNav: 9,
    tIFR: 10,
    tCapt: 11,
    ldg: 12,
    NM: 13,
  },
};
